// ============================================================
//  APP.TSX — DO NOT EDIT THIS FILE
//  To change content, edit config.ts instead.
// ============================================================

import { useEffect, useRef, useState, useCallback } from "react";
import { RESUME_PDF, PROJECTS, SKILLS, LEARNING, SERVICES, CONTACTS, SOCIALS, MARQUEE, ABOUT, TESTIMONIALS } from "./config";

const WORDS = ["BUILDING","CRAFTING","DESIGNING","SHIPPING","LAUNCHING"];

function Loader({ onDone }: { onDone: () => void }) {
  const [pct, setPct] = useState(0);
  const [word, setWord] = useState("BUILDING");
  const start = useRef(performance.now());
  useEffect(() => {
    let raf: number;
    const tick = (now: number) => {
      const p = Math.min(Math.floor(((now - start.current) / 2200) * 100), 100);
      setPct(p); setWord(WORDS[Math.floor((p / 100) * WORDS.length) % WORDS.length]);
      if (p < 100) raf = requestAnimationFrame(tick); else setTimeout(onDone, 200);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [onDone]);
  return (
    <div style={{position:"fixed",inset:0,zIndex:9999,background:"#060606",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:20}}>
      <div style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontSize:13,letterSpacing:6,textTransform:"uppercase",color:"rgba(240,237,232,0.28)",minHeight:18}}>{word}</div>
      <div style={{fontSize:"clamp(70px,12vw,140px)",fontWeight:800,letterSpacing:-6,lineHeight:1,color:"#f0ede8",fontVariantNumeric:"tabular-nums"}}>{String(pct).padStart(3,"0")}</div>
      <div style={{width:200,height:1,background:"rgba(255,255,255,0.07)",borderRadius:1}}>
        <div style={{height:"100%",background:"linear-gradient(90deg,#c8b89a,#8fafc8)",borderRadius:1,width:`${pct}%`,transition:"width 0.04s linear"}}/>
      </div>
    </div>
  );
}

function VideoHero() {
  const vidRef = useRef<HTMLVideoElement>(null);
  const [live, setLive] = useState(false);
  const [heroIn, setHeroIn] = useState(false);
  useEffect(() => {
    setTimeout(() => setHeroIn(true), 50);
    const vid = vidRef.current; if (!vid) return;
    vid.addEventListener("canplay", () => { vid.play().then(() => setLive(true)).catch(() => {}); }, {once:true});
    vid.load();
  }, []);
  const he = (d: number): React.CSSProperties => ({opacity:heroIn?1:0,transform:heroIn?"translateY(0)":"translateY(24px)",transition:`opacity 0.85s ease ${d}ms,transform 0.85s ease ${d}ms`});
  return (
    <section id="hero" style={{position:"relative",minHeight:"100vh",display:"flex",flexDirection:"column",justifyContent:"flex-end",overflow:"hidden",background:"#060606"}}>
      <video ref={vidRef} autoPlay loop muted playsInline style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",zIndex:0}}>
        <source src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260405_170732_8a9ccda6-5cff-4628-b164-059c500a2b41.mp4" type="video/mp4"/>
      </video>
      <div style={{position:"absolute",inset:0,zIndex:1,opacity:0.07,mixBlendMode:"overlay",pointerEvents:"none",backgroundImage:`url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`}}/>
      <div style={{position:"absolute",inset:0,zIndex:2,background:"linear-gradient(to bottom,rgba(0,0,0,0.30) 0%,transparent 40%,rgba(0,0,0,0.60) 100%)",pointerEvents:"none"}}/>
      {live && <div style={{position:"absolute",bottom:20,right:20,zIndex:4,display:"flex",alignItems:"center",gap:6,padding:"6px 12px",borderRadius:100,background:"rgba(0,0,0,0.5)",backdropFilter:"blur(8px)",border:"1px solid rgba(255,255,255,0.1)",fontSize:11,color:"rgba(255,255,255,0.5)",letterSpacing:1}}><span style={{width:5,height:5,borderRadius:"50%",background:"#6EE7B7",display:"inline-block",animation:"blink 2s infinite"}}/><span>LIVE</span></div>}
      <div className="hero-content" style={{position:"relative",zIndex:3,padding:"0 56px 80px",maxWidth:1280,width:"100%"}}>
        <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:16,...he(0)}}>
          <span style={{width:7,height:7,borderRadius:"50%",background:"#c8b89a",flexShrink:0,animation:"blink 2.4s ease-in-out infinite"}}/>
          <span style={{fontSize:10,letterSpacing:4,textTransform:"uppercase",color:"#c8b89a",fontWeight:700}}>Available for Work · 2026</span>
        </div>
        <h1 className="hero-h1" style={{fontWeight:800,letterSpacing:-3,lineHeight:0.95,color:"#f0ede8",margin:0,...he(120)}}>
          Hari Prasad K
          <span className="hero-italic" style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontWeight:400,letterSpacing:-1.5,color:"rgba(240,237,232,0.32)",display:"block",lineHeight:1.1}}>— Developer.</span>
        </h1>
        <div className="hero-bottom" style={{display:"flex",alignItems:"flex-end",justifyContent:"space-between",marginTop:36,gap:32,flexWrap:"wrap"}}>
          <p className="hero-desc" style={{color:"rgba(240,237,232,0.5)",lineHeight:1.85,maxWidth:400,fontWeight:300,margin:0,...he(260)}}>I design and build modern, scalable web applications — focused on performance, clean architecture, and real user experience.</p>
          <div className="hero-btns" style={{display:"flex",gap:10,flexWrap:"wrap",flexShrink:0,...he(420)}}>
            <a href="#projects" className="btn-solid">View Projects →</a>
            <a href="#contact" className="btn-ghost">Get In Touch</a>
            <a href={RESUME_PDF} download="Hari_Prasad_K_Resume.pdf" className="btn-ghost">Resume ↓</a>
          </div>
        </div>
      </div>
    </section>
  );
}

function Nav({ dark, toggleTheme }: { dark:boolean; toggleTheme:()=>void }) {
  const [scrolled,setScrolled]=useState(false);
  const [open,setOpen]=useState(false);
  useEffect(()=>{const h=()=>setScrolled(window.scrollY>60);window.addEventListener("scroll",h,{passive:true});return()=>window.removeEventListener("scroll",h);},[]);
  useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow="";};},[open]);
  // Lock body scroll when menu is open
  useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow="";};},[open]);
  const navBg=scrolled?(dark?"rgba(6,6,6,0.92)":"rgba(245,241,234,0.96)"):"transparent";
  const lc=dark?"rgba(240,237,232,0.55)":"#4a3f30"; const tc=dark?"#f0ede8":"#18150f";
  const links=["about","skills","projects","services","testimonials","contact"];
  return (
    <>
      <nav style={{position:"fixed",top:0,left:0,right:0,zIndex:200,padding:scrolled?"12px 40px":"22px 56px",display:"flex",alignItems:"center",justifyContent:"space-between",background:navBg,backdropFilter:scrolled?"blur(24px)":"none",WebkitBackdropFilter:scrolled?"blur(24px)":"none",borderBottom:scrolled?`1px solid ${dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.08)"}`:"none",transition:"all 0.4s"}}>
        <a href="#hero" style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontSize:20,color:tc,textDecoration:"none",letterSpacing:-0.5,flexShrink:0}}>Hari Prasad K</a>
        <ul className="nav-links-desktop" style={{display:"flex",alignItems:"center",gap:2,listStyle:"none",margin:0,padding:0}}>
          {links.map(s=><li key={s}><a href={`#${s}`} className="nav-link" style={{color:lc,fontSize:13,fontWeight:500,textDecoration:"none",padding:"7px 14px",borderRadius:100,display:"block",transition:"color 0.2s,background 0.2s"}}>{s.charAt(0).toUpperCase()+s.slice(1)}</a></li>)}
        </ul>
        <div style={{display:"flex",alignItems:"center",gap:10}}>
          <button onClick={toggleTheme} style={{width:34,height:34,borderRadius:"50%",border:`1px solid ${dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)"}`,background:dark?"rgba(255,255,255,0.04)":"rgba(255,255,255,0.75)",color:lc,cursor:"pointer",fontSize:14,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{dark?"☀️":"🌙"}</button>
          <a href="mailto:hariprasadk1809@gmail.com" className="hire-btn" style={{padding:"8px 20px",borderRadius:100,background:dark?"#f0ede8":"#18150f",color:dark?"#080808":"#f5f1ea",fontSize:13,fontWeight:600,textDecoration:"none",whiteSpace:"nowrap"}}>Hire Me</a>
          <button className="hamburger" onClick={()=>setOpen(o=>!o)} style={{display:"none",width:34,height:34,borderRadius:8,border:`1px solid ${dark?"rgba(255,255,255,0.12)":"rgba(0,0,0,0.12)"}`,background:"transparent",cursor:"pointer",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:5,padding:8}}>
            <span style={{width:"100%",height:1.5,background:tc,display:"block",borderRadius:2}}/><span style={{width:"100%",height:1.5,background:tc,display:"block",borderRadius:2}}/><span style={{width:"100%",height:1.5,background:tc,display:"block",borderRadius:2}}/>
          </button>
        </div>
      </nav>

      {/* Mobile overlay — outside <nav> so it gets its own stacking context */}
      {open&&(
        <div style={{position:"fixed",inset:0,zIndex:9999,background:dark?"rgba(6,6,6,0.98)":"rgba(245,241,234,0.98)",backdropFilter:"blur(24px)",WebkitBackdropFilter:"blur(24px)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:4}}>
          {/* close */}
          <button onClick={()=>setOpen(false)} style={{position:"absolute",top:20,right:20,width:40,height:40,borderRadius:"50%",border:`1px solid ${dark?"rgba(255,255,255,0.15)":"rgba(0,0,0,0.15)"}`,background:"transparent",color:tc,fontSize:22,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}}>×</button>
          {/* brand */}
          <div style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontSize:18,color:dark?"rgba(240,237,232,0.25)":"rgba(24,21,15,0.25)",marginBottom:20}}>Hari Prasad K</div>
          {/* links */}
          {links.map(s=>(
            <a key={s} href={`#${s}`} onClick={()=>setOpen(false)} style={{color:tc,fontSize:28,fontWeight:700,textDecoration:"none",letterSpacing:-0.5,padding:"10px 0",width:"80%",textAlign:"center"}}>
              {s.charAt(0).toUpperCase()+s.slice(1)}
            </a>
          ))}
          {/* hire me */}
          <a href="mailto:hariprasadk1809@gmail.com" onClick={()=>setOpen(false)} style={{marginTop:24,padding:"14px 40px",borderRadius:100,background:dark?"#f0ede8":"#18150f",color:dark?"#080808":"#f5f1ea",fontSize:15,fontWeight:700,textDecoration:"none"}}>Hire Me</a>
        </div>
      )}
    </>
  );
}

function Marquee({ dark }: { dark:boolean }) {
  const tags=[...MARQUEE,...MARQUEE,...MARQUEE,...MARQUEE];
  const bdr=dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)";
  return (
    <div style={{background:dark?"#080808":"#f5f1ea",borderTop:`1px solid ${bdr}`,borderBottom:`1px solid ${bdr}`,padding:"16px 0",overflow:"hidden",whiteSpace:"nowrap"}}>
      <div style={{display:"inline-flex",animation:"mq 26s linear infinite"}}>
        {tags.map((t,i)=><span key={i} style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontSize:14,color:dark?"rgba(240,237,232,0.18)":"rgba(24,21,15,0.38)",padding:"0 24px",display:"inline-flex",alignItems:"center",gap:24}}>{t}<span style={{width:3,height:3,borderRadius:"50%",background:dark?"rgba(240,237,232,0.18)":"rgba(24,21,15,0.38)",display:"inline-block"}}/></span>)}
      </div>
    </div>
  );
}

function Sec({id,children,dark}:{id:string;children:React.ReactNode;dark:boolean}){
  return <section id={id} className="page-section" style={{padding:"80px 56px",maxWidth:1280,margin:"0 auto",color:dark?"#f0ede8":"#18150f"}}>{children}</section>;
}
function Lbl({t}:{t:string}){return <div style={{fontSize:10,letterSpacing:4,textTransform:"uppercase",color:"#c8b89a",fontWeight:700,marginBottom:10}}>{t}</div>;}
function Title({a,b,dark}:{a:string;b:string;dark:boolean}){
  return <h2 style={{fontSize:"clamp(28px,4vw,50px)",fontWeight:800,letterSpacing:-2,lineHeight:1.06,marginBottom:48,color:dark?"#f0ede8":"#18150f"}}>{a} <em style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontWeight:400,color:dark?"rgba(240,237,232,0.55)":"#4a3f30"}}>{b}</em></h2>;
}

function About({dark}:{dark:boolean}){
  const t2=dark?"rgba(240,237,232,0.55)":"#4a3f30",card=dark?"rgba(255,255,255,0.04)":"rgba(255,255,255,0.75)",bdr=dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)",bg3=dark?"#1c1c1c":"#e2dbd0";

  // Split bio1 around the highlight so we can bold it
  const [before, after] = ABOUT.bio1.includes(ABOUT.internshipHighlight)
    ? [ABOUT.bio1.split(ABOUT.internshipHighlight)[0], ABOUT.bio1.split(ABOUT.internshipHighlight)[1]]
    : [ABOUT.bio1, ""];

  return (
    <Sec id="about" dark={dark}><Lbl t="Who I Am"/><Title a="About" b="Me" dark={dark}/>
      <div className="about-grid" style={{display:"grid",gridTemplateColumns:"7fr 5fr",gap:16,marginBottom:16}}>
        <div className="card-lift" style={{padding:"36px 40px",borderRadius:26,background:card,border:`1px solid ${bdr}`}}>
          <p style={{fontSize:15,color:t2,lineHeight:1.9,fontWeight:300,margin:"0 0 18px"}}>
            {before}
            <strong style={{color:dark?"#f0ede8":"#18150f",fontWeight:600}}>{ABOUT.internshipHighlight}</strong>
            {after}
          </p>
          <p style={{fontSize:15,color:t2,lineHeight:1.9,fontWeight:300,margin:0}}>{ABOUT.bio2}</p>
        </div>
        <div style={{borderRadius:26,border:`1px solid ${bdr}`,overflow:"hidden",background:bg3,minHeight:240}}>
          <img src={ABOUT.photo} alt="Hari Prasad K" style={{width:"100%",height:"100%",objectFit:"cover",objectPosition:"center top",display:"block"}}/>
        </div>
      </div>
      <div className="about-grid3" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16}}>
        <div className="card-lift" style={{padding:28,borderRadius:26,background:card,border:`1px solid ${bdr}`}}>
          <div style={{fontSize:10,letterSpacing:3,textTransform:"uppercase",color:"#c8b89a",fontWeight:700,marginBottom:12}}>Education</div>
          <div style={{fontSize:13,fontWeight:700,marginBottom:6,color:dark?"#f0ede8":"#18150f",lineHeight:1.35}}>{ABOUT.degree}</div>
          <div style={{fontSize:11,color:"#c8b89a",fontWeight:600,marginBottom:6}}>{ABOUT.specialization}</div>
          <div style={{fontSize:11,color:t2,lineHeight:1.5,marginBottom:8}}>{ABOUT.college}</div>
          <div style={{display:"inline-flex",alignItems:"center",gap:6,padding:"3px 10px",borderRadius:100,background:dark?"rgba(200,184,154,0.12)":"rgba(200,184,154,0.2)",border:"1px solid rgba(200,184,154,0.3)"}}>
            <span style={{width:5,height:5,borderRadius:"50%",background:"#6EE7B7",display:"inline-block",flexShrink:0}}/><span style={{fontSize:10,fontWeight:600,color:"#c8b89a"}}>{ABOUT.year}</span>
          </div>
        </div>
        <div className="card-lift" style={{padding:28,borderRadius:26,background:"#c8b89a"}}>
          <div style={{fontSize:10,letterSpacing:3,textTransform:"uppercase",color:"rgba(10,8,4,0.45)",fontWeight:700,marginBottom:12}}>Status</div>
          <div style={{fontSize:19,fontWeight:800,color:"#0a0800",letterSpacing:-0.4,lineHeight:1.25}}>{ABOUT.statusTitle}</div>
          <div style={{fontSize:12,color:"rgba(10,8,0,0.42)",marginTop:6}}>{ABOUT.statusSub}</div>
        </div>
        <div className="card-lift" style={{padding:28,borderRadius:26,background:card,border:`1px solid ${bdr}`}}>
          <div style={{fontSize:10,letterSpacing:3,textTransform:"uppercase",color:"#c8b89a",fontWeight:700,marginBottom:12}}>Currently Learning</div>
          <div style={{marginTop:6}}>{LEARNING.map(l=><span key={l} style={{display:"inline-flex",alignItems:"center",gap:6,padding:"5px 12px",borderRadius:100,margin:4,border:`1px solid ${bdr}`,fontSize:11,color:t2,background:dark?"#111":"#ede8df"}}><span style={{fontSize:10,color:"#c8b89a"}}>→</span>{l}</span>)}</div>
        </div>
      </div>
    </Sec>
  );
}

function WordReveal({dark}:{dark:boolean}){
  const [rev,setRev]=useState(false),ref=useRef<HTMLDivElement>(null),bdr=dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)";
  const words="I build whatever you need — portfolio, invitation, SaaS product, business website. Give me a brief and I will turn it into a premium digital product.".split(" ");
  useEffect(()=>{const obs=new IntersectionObserver(e=>{if(e[0].isIntersecting){setRev(true);obs.disconnect();}},{threshold:0.15});if(ref.current)obs.observe(ref.current);return()=>obs.disconnect();},[]);
  return (
    <div ref={ref} style={{padding:"60px 56px",maxWidth:1280,margin:"0 auto",borderTop:`1px solid ${bdr}`,borderBottom:`1px solid ${bdr}`}}>
      <div style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontSize:"clamp(18px,3vw,38px)",lineHeight:1.65}}>
        {words.map((w,i)=><span key={i} style={{display:"inline",marginRight:"0.28em",color:dark?"#f0ede8":"#18150f",opacity:rev?1:0.15,transition:`opacity 0.4s ease ${i*38}ms`}}>{w} </span>)}
      </div>
    </div>
  );
}

function Skills({dark}:{dark:boolean}){
  const t2=dark?"rgba(240,237,232,0.55)":"#4a3f30",t3=dark?"rgba(240,237,232,0.18)":"rgba(24,21,15,0.38)",bg3=dark?"#1c1c1c":"#e2dbd0",bdr=dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)",card=dark?"rgba(255,255,255,0.04)":"rgba(255,255,255,0.75)";
  const spans=[4,4,4,4,8];
  return (
    <Sec id="skills" dark={dark}><Lbl t="What I Know"/><Title a="Technical" b="Skills" dark={dark}/>
      <div className="skills-grid" style={{display:"grid",gridTemplateColumns:"repeat(12,1fr)",gap:16}}>
        <div className="skills-stat card-lift" style={{gridColumn:"span 8",padding:"36px 40px",borderRadius:26,background:bg3,border:`1px solid ${bdr}`,display:"flex",alignItems:"center",gap:36}}>
          <div style={{fontSize:"clamp(60px,8vw,90px)",fontWeight:800,letterSpacing:-4,lineHeight:1,color:t3,flexShrink:0}}>15+</div>
          <div style={{fontSize:14,color:t2,lineHeight:1.8,fontWeight:300}}>Technologies across frontend, backend, database, cybersecurity, and tooling — ready to build anything you need from scratch.</div>
        </div>
        {Object.entries(SKILLS).map(([cat,pills],i)=>(
          <div key={cat} className={`skill-card-${i} card-lift`} style={{gridColumn:`span ${spans[i]}`,padding:28,borderRadius:26,background:card,border:`1px solid ${bdr}`}}>
            <div style={{fontSize:10,letterSpacing:3.5,textTransform:"uppercase",color:"#c8b89a",fontWeight:700,marginBottom:14}}>{cat}</div>
            <div>{pills.map(p=><span key={p} style={{display:"inline-block",padding:"4px 12px",borderRadius:100,margin:3,background:bg3,border:`1px solid ${bdr}`,fontSize:12,color:t2}}>{p}</span>)}</div>
          </div>
        ))}
      </div>
    </Sec>
  );
}

function Projects({dark}:{dark:boolean}){
  const trackRef=useRef<HTMLDivElement>(null),isDragging=useRef(false),startX=useRef(0),scrollLeft=useRef(0),dragDelta=useRef(0),animRef=useRef<number>(0),pausedRef=useRef(false),posRef=useRef(0);
  const SPEED=0.6,CARD_W=440,GAP=20;
  const t2=dark?"rgba(240,237,232,0.55)":"#4a3f30",bdr=dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)",card=dark?"rgba(255,255,255,0.04)":"rgba(255,255,255,0.75)";
  const cards=[...PROJECTS,...PROJECTS,...PROJECTS,...PROJECTS,...PROJECTS,...PROJECTS];
  const LOOP_W=PROJECTS.length*(CARD_W+GAP);
  const animate=useCallback(()=>{if(!pausedRef.current){posRef.current+=SPEED;if(posRef.current>=LOOP_W)posRef.current-=LOOP_W;if(trackRef.current)trackRef.current.style.transform=`translateX(-${posRef.current}px)`;}animRef.current=requestAnimationFrame(animate);},[LOOP_W]);
  useEffect(()=>{animRef.current=requestAnimationFrame(animate);return()=>cancelAnimationFrame(animRef.current);},[animate]);
  const onME=()=>{pausedRef.current=true;},onML=()=>{pausedRef.current=isDragging.current;};
  const onMD=(e:React.MouseEvent)=>{isDragging.current=true;startX.current=e.clientX;scrollLeft.current=posRef.current;dragDelta.current=0;pausedRef.current=true;};
  const onMM=(e:React.MouseEvent)=>{if(!isDragging.current)return;const dx=e.clientX-startX.current;dragDelta.current=Math.abs(dx);posRef.current=scrollLeft.current-dx;if(posRef.current<0)posRef.current+=LOOP_W;if(posRef.current>=LOOP_W)posRef.current-=LOOP_W;if(trackRef.current)trackRef.current.style.transform=`translateX(-${posRef.current}px)`;};
  const onMU=()=>{isDragging.current=false;};
  const ts=useRef(0);
  const onTS=(e:React.TouchEvent)=>{ts.current=e.touches[0].clientX;scrollLeft.current=posRef.current;pausedRef.current=true;};
  const onTM=(e:React.TouchEvent)=>{const dx=e.touches[0].clientX-ts.current;posRef.current=scrollLeft.current-dx;if(posRef.current<0)posRef.current+=LOOP_W;if(posRef.current>=LOOP_W)posRef.current-=LOOP_W;if(trackRef.current)trackRef.current.style.transform=`translateX(-${posRef.current}px)`;};
  const onTE=()=>{pausedRef.current=false;};
  return (
    <>
      <section id="projects" className="page-section" style={{padding:"80px 56px 0",maxWidth:1280,margin:"0 auto",color:dark?"#f0ede8":"#18150f"}}>
        <Lbl t="What I've Built"/>
<div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}>
  <Title a="Featured" b="Projects" dark={dark}/>
  <div style={{
    fontSize:"clamp(60px,8vw,90px)",
    fontWeight:800,
    letterSpacing:-4,
    lineHeight:1,
    color:dark?"rgba(240,237,232,0.18)":"rgba(24,21,15,0.18)",
    flexShrink:0,
    userSelect:"none"
  }}>
    {PROJECTS.length}+
  </div>
</div>
        <p style={{fontSize:13,color:t2,marginBottom:24,fontWeight:300,lineHeight:1.8,marginTop:-40}}>Drag or hover to pause · Click card to visit project</p>
        <div className="swipe-hint" style={{display:"none",alignItems:"center",gap:10,marginBottom:20,padding:"10px 16px",borderRadius:100,background:dark?"rgba(255,255,255,0.06)":"rgba(0,0,0,0.06)",width:"fit-content"}}>
          <span style={{fontSize:18,animation:"swipe-hint 1.6s ease-in-out infinite"}}>👆</span>
          <span style={{fontSize:12,fontWeight:500,color:dark?"rgba(240,237,232,0.5)":"#4a3f30"}}>Swipe to explore projects</span>
        </div>
      </section>
      <div style={{width:"100%",overflow:"hidden",padding:"4px 0 48px",cursor:"grab",userSelect:"none"}} onMouseEnter={onME} onMouseLeave={onML} onMouseDown={onMD} onMouseMove={onMM} onMouseUp={onMU} onTouchStart={onTS} onTouchMove={onTM} onTouchEnd={onTE}>
        <div ref={trackRef} style={{display:"flex",gap:GAP,width:"max-content",willChange:"transform"}}>
          {cards.map((p,i)=>(
            <div key={i} className="card-lift" style={{width:CARD_W,flexShrink:0,borderRadius:26,display:"flex",flexDirection:"column",background:card,border:`1px solid ${bdr}`,overflow:"hidden",cursor:"pointer"}} onClick={()=>{if(dragDelta.current<8)window.open(p.url,"_blank","noopener,noreferrer");dragDelta.current=0;}}>
              <div style={{width:"100%",height:220,overflow:"hidden",background:dark?"#1c1c1c":"#e2dbd0",flexShrink:0}}>
                <img src={p.img} alt={p.title} loading="lazy" style={{width:"100%",height:"100%",objectFit:"cover",objectPosition:"top center",display:"block",pointerEvents:"none"}}/>
              </div>
              <div style={{padding:"24px 28px 28px",display:"flex",flexDirection:"column",gap:10,flex:1}}>
                <span style={{display:"inline-block",padding:"4px 12px",borderRadius:100,fontSize:11,fontWeight:600,letterSpacing:1.5,textTransform:"uppercase",alignSelf:"flex-start",background:`${p.color}1a`,color:p.color,border:`1px solid ${p.color}30`}}>{p.tag}</span>
                <div style={{fontSize:20,fontWeight:800,letterSpacing:-0.6,color:dark?"#f0ede8":"#18150f"}}>{p.title}</div>
                <div style={{fontSize:13,color:t2,lineHeight:1.65,flex:1}}>{p.line}</div>
                <span style={{fontSize:13,fontWeight:600,display:"inline-flex",alignItems:"center",gap:6,color:p.color,marginTop:4}}>Visit Live →</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

function Services({dark}:{dark:boolean}){
  const t2=dark?"rgba(240,237,232,0.55)":"#4a3f30",bdr=dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)",card=dark?"rgba(255,255,255,0.04)":"rgba(255,255,255,0.75)";
  return (
    <Sec id="services" dark={dark}><Lbl t="What I Offer"/><Title a="My" b="Services" dark={dark}/>
      <div className="services-grid" style={{display:"grid",gridTemplateColumns:"5fr 7fr",gap:16}}>
        <div style={{padding:"40px 36px",borderRadius:26,background:dark?"#f0ede8":"#18150f",color:dark?"#080808":"#f5f1ea",display:"flex",flexDirection:"column",justifyContent:"space-between",minHeight:280}}>
          <div><div style={{fontSize:24,fontWeight:800,letterSpacing:-0.8,lineHeight:1.25}}>Got a project idea?<br/>Let's build it.</div><div style={{fontSize:13,opacity:0.46,lineHeight:1.75,marginTop:12}}>Portfolio, invitation, SaaS, business website — whatever you need.</div></div>
          <a href="mailto:hariprasadk1809@gmail.com" style={{display:"inline-flex",alignItems:"center",gap:8,padding:"10px 20px",borderRadius:100,background:dark?"#080808":"#f5f1ea",color:dark?"#f0ede8":"#18150f",fontSize:13,fontWeight:600,textDecoration:"none",alignSelf:"flex-start",marginTop:24}}>Start a Project →</a>
        </div>
        <div className="services-cards" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          {SERVICES.map(s=><div key={s.name} className="card-lift" style={{padding:28,borderRadius:18,background:card,border:`1px solid ${bdr}`}}><div style={{fontSize:20,marginBottom:12}}>{s.icon}</div><div style={{fontSize:14,fontWeight:700,marginBottom:8,color:dark?"#f0ede8":"#18150f"}}>{s.name}</div><div style={{fontSize:13,color:t2,lineHeight:1.7}}>{s.desc}</div></div>)}
        </div>
      </div>
    </Sec>
  );
}

function Contact({dark}:{dark:boolean}){
  const t2=dark?"rgba(240,237,232,0.55)":"#4a3f30",t3=dark?"rgba(240,237,232,0.18)":"rgba(24,21,15,0.38)",bdr=dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)",card=dark?"rgba(255,255,255,0.04)":"rgba(255,255,255,0.75)";
  return (
    <Sec id="contact" dark={dark}><Lbl t="Get In Touch"/><Title a="Let's" b="Talk" dark={dark}/>
      <div className="contact-grid" style={{display:"grid",gridTemplateColumns:"7fr 5fr",gap:16}}>
        <div style={{padding:"44px 48px",borderRadius:26,background:"rgba(255,255,255,0.015)",backdropFilter:"blur(32px)",WebkitBackdropFilter:"blur(32px)",border:`1px solid ${bdr}`,display:"flex",flexDirection:"column",justifyContent:"space-between",minHeight:300}}>
          <div><div style={{fontSize:"clamp(22px,3vw,40px)",fontWeight:800,letterSpacing:-2,lineHeight:1.1,color:dark?"#f0ede8":"#18150f"}}>Have a project<br/>or <em style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontWeight:400,color:t2}}>opportunity?</em></div><div style={{fontSize:14,color:t2,lineHeight:1.82,fontWeight:300,marginTop:14,maxWidth:360}}>I'm always open to new ideas, collaborations, and job offers. Reach out and let's create something great together.</div></div>
          <a href="mailto:hariprasadk1809@gmail.com" style={{display:"inline-flex",alignItems:"center",gap:8,padding:"12px 24px",borderRadius:100,background:dark?"#f0ede8":"#18150f",color:dark?"#080808":"#f5f1ea",fontSize:14,fontWeight:700,textDecoration:"none",marginTop:28,alignSelf:"flex-start"}}>Send an Email →</a>
        </div>
        <div style={{display:"flex",flexDirection:"column",gap:12}}>
          {CONTACTS.map(c=><a key={c.lbl} href={c.href} target="_blank" rel="noopener noreferrer" className="clink-item card-lift" style={{padding:"20px 22px",borderRadius:18,background:card,border:`1px solid ${bdr}`,textDecoration:"none",color:dark?"#f0ede8":"#18150f",display:"flex",alignItems:"center",gap:14,minHeight:64}}><span style={{fontSize:22,width:36,textAlign:"center",flexShrink:0}}>{c.ico}</span><span style={{overflow:"hidden"}}><span style={{fontSize:10,letterSpacing:2,textTransform:"uppercase",color:t3,display:"block",marginBottom:4}}>{c.lbl}</span><span className="clink-val" style={{fontSize:13,fontWeight:500,display:"block",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{c.val}</span></span></a>)}
        </div>
      </div>
    </Sec>
  );
}

/* ── TESTIMONIALS WALL ───────────────────────────────────────── */
function Testimonials({dark}:{dark:boolean}){
  const t2  = dark?"rgba(240,237,232,0.55)":"#4a3f30";
  const bdr = dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)";
  const card = dark?"rgba(255,255,255,0.04)":"rgba(255,255,255,0.85)";

  if(!TESTIMONIALS||TESTIMONIALS.length===0) return null;

  // Split into 3 columns as evenly as possible
  const col1:typeof TESTIMONIALS=[], col2:typeof TESTIMONIALS=[], col3:typeof TESTIMONIALS=[];
  TESTIMONIALS.forEach((t,i)=>{
    if(i%3===0) col1.push(t);
    else if(i%3===1) col2.push(t);
    else col3.push(t);
  });

  // Duplicate each column for seamless loop
  const c1=[...col1,...col1,...col1,...col1];
  const c2=[...col2,...col2,...col2,...col2];
  const c3=[...col3,...col3,...col3,...col3];

  return (
    <section id="testimonials" style={{padding:"80px 0",color:dark?"#f0ede8":"#18150f",overflow:"hidden"}}>

      {/* header */}
      <div className="testi-header" style={{padding:"0 56px",maxWidth:1280,margin:"0 auto 32px"}}>
        <Lbl t="Client Reviews"/>
        {/* Separate lines to prevent overlap on mobile */}
        <h2 style={{fontSize:"clamp(28px,4vw,50px)",fontWeight:800,letterSpacing:-2,lineHeight:1.1,marginBottom:12,color:dark?"#f0ede8":"#18150f"}}>
          What Clients{" "}
          <em style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontWeight:400,color:dark?"rgba(240,237,232,0.55)":"#4a3f30"}}>Say</em>
        </h2>
        <p className="testi-subtitle" style={{fontSize:13,color:t2,fontWeight:300,lineHeight:1.6}}>
          <span className="testi-hover-text">Hover to pause · </span>Real feedback from real clients
        </p>
      </div>

      {/* ── DESKTOP: 3-column wall ── */}
      <div className="testi-desktop-wall" style={{position:"relative",maxWidth:1280,margin:"0 auto",padding:"0 56px"}} >
        <div className="testi-wall-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:16,height:600,overflow:"hidden"}}>
          <TestiColumn dark={dark} cards={c1} direction="up"   card={card} bdr={bdr} t2={t2} loopLen={col1.length}/>
          <TestiColumn dark={dark} cards={c2} direction="down" card={card} bdr={bdr} t2={t2} loopLen={col2.length}/>
          <div className="testi-col3" style={{overflow:"hidden",height:"100%"}}>
            <TestiColumn dark={dark} cards={c3} direction="up" card={card} bdr={bdr} t2={t2} loopLen={col3.length}/>
          </div>
        </div>
        {/* fade top edge */}
        <div style={{position:"absolute",top:0,left:0,right:0,height:80,background:`linear-gradient(to bottom,${dark?"#080808":"#f5f1ea"},transparent)`,zIndex:10,pointerEvents:"none"}}/>
        {/* fade bottom edge */}
        <div style={{position:"absolute",bottom:0,left:0,right:0,height:80,background:`linear-gradient(to top,${dark?"#080808":"#f5f1ea"},transparent)`,zIndex:10,pointerEvents:"none"}}/>
      </div>

      {/* ── MOBILE: single column scrolling feed ── */}
      <div className="testi-mobile-feed" style={{display:"none",position:"relative",overflow:"hidden",height:560}}>
        <TestiColumn dark={dark} cards={[...TESTIMONIALS,...TESTIMONIALS,...TESTIMONIALS,...TESTIMONIALS,...TESTIMONIALS]} direction="up" card={card} bdr={bdr} t2={t2} loopLen={TESTIMONIALS.length} mobile={true}/>
        {/* fade top */}
        <div style={{position:"absolute",top:0,left:0,right:0,height:80,background:`linear-gradient(to bottom,${dark?"#080808":"#f5f1ea"},transparent)`,zIndex:10,pointerEvents:"none"}}/>
        {/* fade bottom */}
        <div style={{position:"absolute",bottom:0,left:0,right:0,height:80,background:`linear-gradient(to top,${dark?"#080808":"#f5f1ea"},transparent)`,zIndex:10,pointerEvents:"none"}}/>
      </div>

      {/* verified note */}
      <div className="testi-header" style={{padding:"20px 56px 0",maxWidth:1280,margin:"0 auto",display:"flex",alignItems:"center",gap:8}}>
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#c8b89a" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/>
        </svg>
        <span style={{fontSize:12,color:dark?"rgba(240,237,232,0.18)":"rgba(24,21,15,0.28)"}}>
          Reviews from real clients — verified projects
        </span>
      </div>
    </section>
  );
}

/* ── SINGLE COLUMN (scrolls up or down) ─────────────────────── */
function TestiColumn({dark,cards,direction,card,bdr,t2,loopLen,mobile=false}:{
  dark:boolean;
  cards:typeof TESTIMONIALS;
  direction:"up"|"down";
  card:string;bdr:string;t2:string;
  loopLen:number;
  mobile?:boolean;
}){
  const trackRef  = useRef<HTMLDivElement>(null);
  const pausedRef = useRef(false);
  const posRef    = useRef(0);
  const animRef   = useRef<number>(0);
  const SPEED     = direction==="up" ? 0.4 : -0.4;

  // measure total height of one loop
  const [loopH, setLoopH] = useState(0);
  useEffect(()=>{
    if(!trackRef.current) return;
    const measure = () => {
      if(trackRef.current && trackRef.current.scrollHeight > 0){
        setLoopH(trackRef.current.scrollHeight / (cards.length / loopLen));
      }
    };
    // Measure immediately and again after paint
    measure();
    const t1 = setTimeout(measure, 100);
    const t2 = setTimeout(measure, 500);
    // Also watch for size changes
    const ro = new ResizeObserver(measure);
    ro.observe(trackRef.current);
    return () => { clearTimeout(t1); clearTimeout(t2); ro.disconnect(); };
  },[cards.length, loopLen]);

  // start down-column from middle
  useEffect(()=>{
    if(direction==="down" && loopH>0) posRef.current = loopH/2;
  },[direction, loopH]);

  const animate = useCallback(()=>{
    if(!pausedRef.current && loopH>0){
      posRef.current += SPEED;
      if(posRef.current >= loopH) posRef.current -= loopH;
      if(posRef.current < 0)      posRef.current += loopH;
      if(trackRef.current) trackRef.current.style.transform=`translateY(-${posRef.current}px)`;
    }
    animRef.current = requestAnimationFrame(animate);
  },[SPEED, loopH]);

  useEffect(()=>{
    animRef.current = requestAnimationFrame(animate);
    return ()=>cancelAnimationFrame(animRef.current);
  },[animate]);

  return (
    <div
      style={{overflow:"hidden",height:"100%",padding: mobile ? "0 20px" : undefined}}
      onMouseEnter={()=>{ pausedRef.current=true; }}
      onMouseLeave={()=>{ pausedRef.current=false; }}
    >
      <div ref={trackRef} style={{display:"flex",flexDirection:"column",gap: mobile ? 16 : 12,willChange:"transform"}}>
        {cards.map((t,i)=>(
          <div key={i} style={{borderRadius:20,background:card,border:`1px solid ${bdr}`,padding: mobile ? "24px 24px 20px" : "22px 22px 18px",display:"flex",flexDirection:"column",gap:14,flexShrink:0,position:"relative",overflow:"hidden"}}>

            {/* quote watermark */}
            <div style={{position:"absolute",top:-12,right:8,fontSize:80,fontFamily:"'Instrument Serif',serif",fontStyle:"italic",color:dark?"rgba(200,184,154,0.06)":"rgba(200,184,154,0.12)",lineHeight:1,pointerEvents:"none",userSelect:"none"}}>"</div>

            {/* stars */}
            <div style={{display:"flex",gap:3}}>
              {Array.from({length:5}).map((_,si)=>(
                <svg key={si} width="12" height="12" viewBox="0 0 24 24"
                  fill={si<t.rating?"#c8b89a":"none"}
                  stroke="#c8b89a" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                  <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
                </svg>
              ))}
            </div>

            {/* review text */}
            <p style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontSize: mobile ? 16 : 14,color:dark?"rgba(240,237,232,0.85)":"#18150f",lineHeight:1.75,position:"relative",zIndex:1,margin:0}}>
              "{t.review}"
            </p>

            {/* divider */}
            <div style={{height:1,background:bdr}}/>

            {/* client info */}
            <div style={{display:"flex",alignItems:"center",gap:10}}>
              {/* AVATAR — initials on colored circle */}
              <div style={{
                width:34,height:34,borderRadius:"50%",
                background:t.avatarBg||"#c8b89a",
                display:"flex",alignItems:"center",justifyContent:"center",
                flexShrink:0,
                fontSize:11,fontWeight:800,
                color:"#080808",
                letterSpacing:0.5,
                fontFamily:"'Inter',sans-serif",
              }}>
                {t.avatar}
              </div>
              <div style={{flex:1,overflow:"hidden"}}>
                <div style={{fontSize:12,fontWeight:700,color:dark?"#f0ede8":"#18150f",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{t.name}</div>
                <div style={{fontSize:10,color:t2,marginTop:1}}>{t.role}</div>
              </div>
              <span style={{padding:"2px 8px",borderRadius:100,fontSize:9,fontWeight:700,letterSpacing:0.5,textTransform:"uppercase",background:"rgba(200,184,154,0.1)",color:"#c8b89a",border:"1px solid rgba(200,184,154,0.22)",flexShrink:0,whiteSpace:"nowrap",maxWidth:100,overflow:"hidden",textOverflow:"ellipsis"}}>
                {t.project}
              </span>
            </div>

          </div>
        ))}
      </div>
    </div>
  );
}

const GH=<svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"/></svg>;
const LI=<svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>;
const EM=<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 01-2.06 0L2 7"/></svg>;
const UP=<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="m18 15-6-6-6 6"/></svg>;
const ICON_MAP:Record<string,React.ReactNode>={GitHub:GH,LinkedIn:LI,Email:EM};

function Footer({dark,toggleTheme}:{dark:boolean;toggleTheme:()=>void}){
  const bdr=dark?"rgba(255,255,255,0.07)":"rgba(0,0,0,0.1)",t2=dark?"rgba(240,237,232,0.55)":"#4a3f30",t3=dark?"rgba(240,237,232,0.25)":"rgba(24,21,15,0.35)",card=dark?"rgba(255,255,255,0.05)":"rgba(0,0,0,0.04)";
  return (
    <footer style={{borderTop:`1px solid ${bdr}`,background:dark?"#080808":"#f5f1ea"}} className="footer-inner">
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:16,padding:"32px 0 24px",borderBottom:`1px solid ${bdr}`}}>
        <div><div style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontSize:22,color:dark?"#f0ede8":"#18150f",marginBottom:4}}>Hari Prasad K</div><div style={{fontSize:12,color:t2,fontWeight:300}}>Full-Stack Developer · Cybersecurity Enthusiast</div></div>
        <div style={{display:"flex",alignItems:"center",gap:8}}>
          {SOCIALS.map(s=><a key={s.label} href={s.href} target="_blank" rel="noopener noreferrer" title={s.label} style={{width:40,height:40,borderRadius:"50%",border:`1px solid ${bdr}`,background:card,color:t2,display:"flex",alignItems:"center",justifyContent:"center",textDecoration:"none",transition:"all 0.2s"}} onMouseEnter={e=>{const el=e.currentTarget as HTMLElement;el.style.borderColor="#c8b89a";el.style.color="#c8b89a";el.style.transform="translateY(-2px)";}} onMouseLeave={e=>{const el=e.currentTarget as HTMLElement;el.style.borderColor=bdr;el.style.color=t2;el.style.transform="translateY(0)";}}>{ICON_MAP[s.label]}</a>)}
        </div>
        <button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} style={{display:"flex",alignItems:"center",gap:8,padding:"10px 20px",borderRadius:100,border:`1px solid ${bdr}`,background:card,color:t2,cursor:"pointer",fontSize:12,fontWeight:600,transition:"all 0.2s"}} onMouseEnter={e=>{const el=e.currentTarget as HTMLElement;el.style.borderColor="#c8b89a";el.style.color="#c8b89a";}} onMouseLeave={e=>{const el=e.currentTarget as HTMLElement;el.style.borderColor=bdr;el.style.color=t2;}}>{UP} Back to Top</button>
      </div>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:12,padding:"18px 0",color:t3,fontSize:11}}>
        <span>© 2026 Hari Prasad K · All Rights Reserved</span>
        <button onClick={toggleTheme} style={{width:32,height:32,borderRadius:"50%",border:`1px solid ${bdr}`,background:card,color:t2,cursor:"pointer",fontSize:13,display:"flex",alignItems:"center",justifyContent:"center"}}>{dark?"☀️":"🌙"}</button>
      </div>
    </footer>
  );
}

function FabTop(){
  const [show,setShow]=useState(false);
  useEffect(()=>{const h=()=>setShow(window.scrollY>400);window.addEventListener("scroll",h,{passive:true});return()=>window.removeEventListener("scroll",h);},[]);
  return <button className={`fab-top${show?" show":""}`} onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>{UP}</button>;
}

const CSS=`
  @import url('https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@300;400;500;600;700;800&display=swap');
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
  html,body{overflow-x:hidden;width:100%;max-width:100%}
  html{scroll-behavior:smooth}
  ::-webkit-scrollbar{display:none;width:0;height:0}
  *{scrollbar-width:none;-ms-overflow-style:none}
  @keyframes blink{0%,100%{opacity:1}50%{opacity:0.2}}
  @keyframes mq{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}
  @keyframes swipe-hint{0%{transform:translateX(0);opacity:1}50%{transform:translateX(-14px);opacity:0.5}100%{transform:translateX(0);opacity:1}}
  .hero-h1{font-size:clamp(40px,7vw,96px)}.hero-italic{font-size:clamp(36px,6.4vw,88px)}.hero-desc{font-size:clamp(13px,1.4vw,15px)}.hero-content{padding:0 56px 80px}
  .btn-solid{padding:12px 28px;border-radius:100px;background:#f0ede8;color:#080808;font-weight:700;font-size:14px;text-decoration:none;display:inline-flex;align-items:center;gap:8px;box-shadow:0 2px 0 rgba(0,0,0,0.35),0 4px 12px rgba(0,0,0,0.25),inset 0 1px 0 rgba(255,255,255,0.9);transition:transform 0.15s ease,box-shadow 0.15s ease;cursor:pointer;position:relative;top:0}
  .btn-solid:hover{transform:translateY(-2px);box-shadow:0 4px 0 rgba(0,0,0,0.35),0 8px 20px rgba(0,0,0,0.3),inset 0 1px 0 rgba(255,255,255,0.9)}
  .btn-solid:active{transform:translateY(1px);box-shadow:0 1px 0 rgba(0,0,0,0.35),0 2px 6px rgba(0,0,0,0.2),inset 0 1px 0 rgba(255,255,255,0.9)}
  .btn-ghost{padding:12px 28px;border-radius:100px;background:rgba(255,255,255,0.05);color:rgba(240,237,232,0.7);font-weight:500;font-size:14px;text-decoration:none;border:1px solid rgba(255,255,255,0.2);display:inline-flex;align-items:center;gap:8px;box-shadow:0 2px 0 rgba(0,0,0,0.3),0 4px 12px rgba(0,0,0,0.15),inset 0 1px 0 rgba(255,255,255,0.08);transition:transform 0.15s ease,box-shadow 0.15s ease,background 0.15s ease,color 0.15s ease;cursor:pointer;position:relative;top:0;backdrop-filter:blur(8px)}
  .btn-ghost:hover{transform:translateY(-2px);background:rgba(255,255,255,0.1);color:rgba(240,237,232,0.95);box-shadow:0 4px 0 rgba(0,0,0,0.3),0 8px 20px rgba(0,0,0,0.2),inset 0 1px 0 rgba(255,255,255,0.12)}
  .btn-ghost:active{transform:translateY(1px);box-shadow:0 1px 0 rgba(0,0,0,0.3),0 2px 6px rgba(0,0,0,0.15),inset 0 1px 0 rgba(255,255,255,0.08)}
  .nav-link:hover{color:#c8b89a !important;background:rgba(255,255,255,0.07) !important}
  .hire-btn{display:block}.hamburger{display:none !important}.nav-links-desktop{display:flex !important}
  .swipe-hint{display:none}.clink-item{min-height:64px}.footer-inner{padding:0 56px}
  .fab-top{display:none;position:fixed;bottom:24px;right:20px;z-index:150;width:44px;height:44px;border-radius:50%;background:#c8b89a;color:#080808;border:none;cursor:pointer;align-items:center;justify-content:center;box-shadow:0 4px 20px rgba(0,0,0,0.3);transition:transform 0.2s,opacity 0.3s;opacity:0;pointer-events:none}
  .fab-top.show{opacity:1;pointer-events:auto}
  .testi-hover-text{display:inline}
  .testi-mobile-feed{display:none !important}
  .testi-desktop-wall{display:block}
  /* tactile cards */
  .card-lift{transition:transform 0.2s ease,box-shadow 0.2s ease !important}
  .card-lift:hover{transform:translateY(-4px) !important;box-shadow:0 12px 32px rgba(0,0,0,0.35),0 2px 8px rgba(0,0,0,0.2) !important}
  .card-lift:active{transform:translateY(-1px) !important}
  @media(max-width:1024px){
    .skills-grid{grid-template-columns:repeat(6,1fr) !important}
    .skills-stat{grid-column:span 6 !important}
    .skill-card-0,.skill-card-1,.skill-card-2,.skill-card-3{grid-column:span 3 !important}
    .skill-card-4{grid-column:span 6 !important}
    .testi-wall-grid{grid-template-columns:1fr 1fr 1fr !important}
    .testi-wrap{padding:0 32px !important}
    .testi-header{padding-left:32px !important;padding-right:32px !important}
  }
  @media(max-width:768px){
    .hero-content{padding:0 20px 56px !important}
    .hero-h1{font-size:clamp(28px,8.5vw,60px) !important;letter-spacing:-2px !important}
    .hero-italic{font-size:clamp(24px,7.5vw,54px) !important;letter-spacing:-1px !important}
    .hero-bottom{flex-direction:column !important;align-items:flex-start !important;gap:20px !important}
    .hero-btns{flex-wrap:wrap !important;gap:8px !important}
    .hero-desc{font-size:14px !important;max-width:100% !important}
    .page-section{padding:56px 20px !important}
    .about-grid{grid-template-columns:1fr !important}
    .about-grid3{grid-template-columns:1fr !important}
    .skills-grid{grid-template-columns:1fr !important}
    .skills-stat{grid-column:span 1 !important;flex-direction:column !important;gap:16px !important}
    .skill-card-0,.skill-card-1,.skill-card-2,.skill-card-3,.skill-card-4{grid-column:span 1 !important}
    .services-grid{grid-template-columns:1fr !important}
    .services-cards{grid-template-columns:1fr 1fr !important}
    .contact-grid{grid-template-columns:1fr !important}
    .nav-links-desktop{display:none !important}
    .hamburger{display:flex !important}
    .hire-btn{display:none !important}
    .swipe-hint{display:flex !important}
    .clink-item{padding:18px 20px !important;min-height:72px !important}
    .clink-val{font-size:12px !important;word-break:break-all !important}
    .footer-inner{padding:0 20px !important}
    .fab-top{display:flex !important}
    .testi-mobile-feed{display:block !important}
    .testi-desktop-wall{display:none !important}
    .testi-wrap{padding:0 20px !important}
    .testi-header{padding-left:20px !important;padding-right:20px !important}
    .testi-hover-text{display:none !important}
  }
  @media(max-width:480px){
    .hero-content{padding:0 18px 48px !important}
    .hero-h1{font-size:clamp(26px,9vw,46px) !important;letter-spacing:-1.5px !important}
    .hero-italic{font-size:clamp(22px,8vw,42px) !important}
    .hero-btns{gap:6px !important}
    .services-cards{grid-template-columns:1fr !important}
    .btn-solid,.btn-ghost{font-size:13px !important;padding:10px 18px !important}
    .clink-item{padding:16px 18px !important;min-height:68px !important}
    .testi-wall-grid{grid-template-columns:1fr 1fr !important;gap:10px !important;height:480px !important}
    .testi-wrap{padding:0 16px !important}
    .testi-header{padding-left:16px !important;padding-right:16px !important}
    .footer-inner{padding:0 16px !important}
  }
  @media(max-width:375px){
    .hero-h1{font-size:clamp(24px,8.5vw,40px) !important}
    .hero-italic{font-size:clamp(20px,7.5vw,36px) !important}
    .page-section{padding:48px 16px !important}
    .testi-wall-grid{height:440px !important}
  }
`;

export default function App(){
  const [loaded,setLoaded]=useState(false),[dark,setDark]=useState(true);
  const toggle=()=>setDark(d=>!d);
  return (
    <div style={{background:dark?"#080808":"#f5f1ea",color:dark?"#f0ede8":"#18150f",fontFamily:"'Inter',sans-serif",overflowX:"hidden",overflowY:"auto",minHeight:"100vh",transition:"background 0.4s,color 0.4s",position:"relative",maxWidth:"100vw"}}>
      <style>{CSS}</style>
      {!loaded&&<Loader onDone={()=>setLoaded(true)}/>}
      {loaded&&<><Nav dark={dark} toggleTheme={toggle}/><VideoHero/><Marquee dark={dark}/><About dark={dark}/><WordReveal dark={dark}/><Skills dark={dark}/><Projects dark={dark}/><Services dark={dark}/><Testimonials dark={dark}/><Contact dark={dark}/><Footer dark={dark} toggleTheme={toggle}/><FabTop/></>}
    </div>
  );
}